# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-overlay = {
    pname = "emacs-overlay";
    version = "5b8f060a63e9edc248eee5a258f5abcd2f128caa";
    src = fetchTarball {
      url = "https://github.com/nix-community/emacs-overlay/archive/5b8f060a63e9edc248eee5a258f5abcd2f128caa.tar.gz";
      sha256 = "sha256-y9Ff62SXccO34iqDcy1+Fj0UvkIq7H8o4zbeQo/hXPE=";
    };
    date = "2026-08-28";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "26.11pre1062397.9fbb54b33e91";
    src = fetchTarball {
      url = "https://releases.nixos.org/nixos/unstable/nixos-26.11pre1062397.9fbb54b33e91/nixexprs.tar.zst";
      sha256 = "sha256-IkjmqLoWzeqBAi1VIkdhDLMGjQDJ4suEDp59Zwxpswg=";
    };
  };
}
