# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-overlay = {
    pname = "emacs-overlay";
    version = "fb0d6e46ad922999f91de177f80e60c2765ccb1c";
    src = fetchTarball {
      url = "https://github.com/nix-community/emacs-overlay/archive/fb0d6e46ad922999f91de177f80e60c2765ccb1c.tar.gz";
      sha256 = "sha256-RD/Yw726NrHSjA4XYWXN+FjQ8MiAGMxADrZcgtGULt4=";
    };
    date = "2026-09-25";
  };
  everforest = {
    pname = "everforest";
    version = "ba61a881b5d57810eef76baae01c951d1e6c2ceb";
    src = fetchTarball {
      url = "https://github.com/theorytoe/everforest-emacs/archive/ba61a881b5d57810eef76baae01c951d1e6c2ceb.tar.gz";
      sha256 = "sha256-p8D27i5EZp37QVi9IffJqXnnFxUaaAc9BfzIzrje66U=";
    };
    date = "2025-08-30";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "4975466d324710c576dc11ad614684e6bd8cad8e";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/4975466d324710c576dc11ad614684e6bd8cad8e.tar.gz";
      sha256 = "sha256-xJ+X4hBtOcAFGBOe5nAMyMUeF9foJBmIOu3NjBqBycU=";
    };
    date = "2026-09-23";
  };
}
