# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-overlay = {
    pname = "emacs-overlay";
    version = "4b849481911296c843cf1e958dc0c99bfa112bf0";
    src = fetchTarball {
      url = "https://github.com/nix-community/emacs-overlay/archive/4b849481911296c843cf1e958dc0c99bfa112bf0.tar.gz";
      sha256 = "sha256-kwF+AEtqMdvxjDe3mmXcgto8078KxBPfw3zgs7rYaRY=";
    };
    date = "2026-09-25";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "4975466d324710c576dc11ad614684e6bd8cad8e";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/4975466d324710c576dc11ad614684e6bd8cad8e.tar.gz";
      sha256 = "sha256-xJ+X4hBtOcAFGBOe5nAMyMUeF9foJBmIOu3NjBqBycU=";
    };
    date = "2026-09-23";
  };
}
